name: Build EC2 Base AMI

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region to build the AMI in"
        required: true
        default: "us-east-1"
      vpc_name:
        description: "Name tag of the VPC for the build instance"
        required: true
        default: "vpc-east-1"
      build_subnet_name:
        description: "Name tag of the build subnet (must have internet access)"
        required: true
        default: "public-subnet-a"

jobs:
  packer:
    uses: rdavis542/aws-github-workflows/.github/workflows/packer-build.yml@main
    with:
      packer_file: ec2-base.pkr.hcl
    secrets: inherit
